# required params
k: 8
alphabet: 2 # choices 0-5 or names (see alphabet module), or None

# input/output params
input_dir: input # defaults to 'input'
input_file_exts: ["fasta", "fna", "faa", "fa"] # specify valid input file extensions
input_file_regex: ".*" # regex to parse family from filename
nested_output: False # if True, saves into {save_dir}/{alphabet name}/{k}

# scoring params
score:
  scaler: True
  scaler_kwargs: { "n": 0.25 }
  labels: None
  lname: None # label name

# cluster params
cluster:
  method: "agglomerative"
  params:
    {
      n_clusters: None,
      distance_threshold: 95,
      linkage: ward,
    }
  cluster_plots: True

  # clustering distance matrix params
  min_rep:
  max_rep:
  save_matrix: False
  dist_thresh: 100

# model params
model:
  cv: 5
  random_state: None

# search params
model_dir: "/path/to/output/model/"
basis_dir: "/path/to/output/kmerize/"
score_dir: "/path/to/output/scoring/"

# learnapp params 
learnapp:
  save_apply_associations: False

